-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Table: profiles (Minimal version for user linkage, linked to auth.users if needed later)
-- In a real Supabase Auth setup, this often triggers on auth.users insert.
-- For now, we manually create it or assume it exists.
create table if not exists public.profiles (
  id uuid primary key default uuid_generate_v4(),
  username text,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Table: mission
-- Table: missions
create table if not exists public.missions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  title text,
  description text,
  location_name text,
  location_address text,
  gps_lat float,
  gps_lng float,
  captured_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Table: detections
create table if not exists public.detections (
  id bigint generated by default as identity primary key,
  mission_id bigint references public.missions(id) on delete cascade,
  image_url text,
  label text,
  is_manual boolean default false,
  confidence float,
  bbox jsonb, -- Efficient JSON storage for bounding boxes [x, y, w, h]
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Add simple RLS (Row Level Security) - Optional but recommended
-- For development, we might temporarily disable or allow all
alter table public.profiles enable row level security;
alter table public.missions enable row level security;
alter table public.detections enable row level security;

-- Policy: Allow read/write access to everyone (public) for development
-- WARNING: Update this for production!
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Public missions are viewable by everyone." on public.missions for select using (true);
create policy "Public missions are insertable by everyone." on public.missions for insert with check (true);
create policy "Public detections are viewable by everyone." on public.detections for select using (true);
create policy "Public detections are insertable by everyone." on public.detections for insert with check (true);
